name: Continuous integration

on:
  - push
  - pull_request

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    outputs:
      changelog: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42.0.2

  run_unitary_tests:
    name: Run clippy and unitary tests
    runs-on: ubuntu-latest

    needs: changelog
    if: |
      contains(needs.changelog.outputs.changelog, 'src') ||
      contains(needs.changelog.outputs.changelog, 'Cargo.toml')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Cargo clippy
        uses: actions-rs/clippy@master

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
